apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: mqtt-benchmark
  name: mqtt-benchmark
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: mqtt-benchmark
      qcloud-app: mqtt-benchmark
  template:
    metadata:
      annotations:
        prometheus.io/port: "2112"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        k8s-app: mqtt-benchmark
        qcloud-app: mqtt-benchmark
    spec:
      affinity: {}
      containers:
      - args:
        - '/app/mqtt-benchmark pub -S 10.0.3.11:1883 -u bench -P bench -c 10000 --with-timestamp
          -R 1000 -n pub --metrics-port 2112 --log-level=info --topic homeup/%i/%d
          --topic-num 30 --payload-size 100 --qos 1 --rate 1 '
        command:
        - sh
        - -c
        image: zzjcool/mqtt-benchmark:latest
        imagePullPolicy: Always
        name: mqtt-benchmark
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "4"
            memory: 8Gi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
